name: organizer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  provider:
  google_fonts:
  shared_preferences:
  font_awesome_flutter:
  table_calendar:
  sqflite:
  intl:

  cupertino_icons: ^0.1.3
  form_field_validator: ^1.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.7
  uuid: ^2.2.2
  get_it: ^5.0.3
  flutter_local_notifications: ^3.0.3
  timezone: ^0.5.6
  flutter_native_timezone: ^1.0.4
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/appLogo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/signin.png
    - assets/logo.png
    - assets/logo2.png
    - assets/appLogo.png

